In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
import math
# Load pylab
%pylab inline

destinations = pd.read_csv("data/my_submission.csv")
test = pd.read_csv("data/test.csv")
train = pd.read_csv("data/train.csv")
firstColumnInd = destinations["Id"]

Populating the interactive namespace from numpy and matplotlib

In [92]:
print train.shape
print test.shape
print destinations.shape

(10886, 15)
(6493, 14)
(6493, 2)

In [127]:
train.describe()

,instant,season,yr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt,cmnth,smnth,chr,shr,cseason,sseason,cweekday,sweekday
count,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000,10886.000000
mean,8537.421183,2.506614,0.501929,0.028569,2.998622,0.680875,1.418427,0.493436,0.473102,0.618865,0.191036,4.552561,0.434912,0.737682,-0.131761,0.477532,0.906995,0.382346,0.843590,0.436222
std,5026.363303,1.116174,0.500019,0.166599,2.007770,0.466159,0.633839,0.190039,0.169492,0.192450,0.121859,1.489043,0.435911,0.276915,0.744090,0.448333,0.069288,0.162400,0.147618,0.276194
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.015200,0.000000,0.000000,0.000000,-0.332604,0.158484,-0.999139,-0.495987,0.804110,0.158484,0.577666,0.000000
25%,4282.250000,2.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.470000,0.104500,3.737670,-0.020752,0.594481,-0.906466,0.117378,0.804110,0.312962,0.699732,0.158484
50%,8666.500000,3.000000,1.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.620000,0.194000,4.976734,0.440999,0.897507,-0.332604,0.594481,0.888163,0.459529,0.888163,0.459529
75%,13016.750000,4.000000,1.000000,0.000000,5.000000,1.000000,2.000000,0.640000,0.621200,0.770000,0.253700,5.648974,0.804110,0.983860,0.577666,0.897507,0.949766,0.594481,0.987362,0.714406
max,17093.000000,4.000000,1.000000,1.000000,6.000000,1.000000,4.000000,1.000000,0.909100,1.000000,0.850700,6.884487,0.987362,0.999785,1.000000,0.999785,0.987362,0.594481,1.000000,0.816273

In [93]:
train.head(5)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,1

In [94]:
train["dteday"] = pd.to_datetime(train["dteday"])
#train["year"] = train["dteday"].dt.year
#train["day"] = train["dteday"].dt.day

train.drop('dteday', axis=1, inplace=True)
#train.drop('yr', axis=1, inplace=True)
train["cnt"] = log(train["cnt"])

train["cmnth"] = cos(train["mnth"]/(2*math.pi))
train["smnth"] = sin(train["mnth"]/(2*math.pi))
train["chr"] = cos(train["hr"]/(2*math.pi))
train["shr"] = sin(train["hr"]/(2*math.pi))
train["cseason"] = cos(train["season"]/(2*math.pi))
train["sseason"] = sin(train["season"]/(2*math.pi))
train["cweekday"] = cos(train["weekday"]/(2*math.pi))
train["sweekday"] = sin(train["weekday"]/(2*math.pi))


train.drop('hr', axis=1, inplace=True)
train.drop('mnth', axis=1, inplace=True)


test["dteday"] = pd.to_datetime(test["dteday"])
#test["year"] = test["dteday"].dt.year

test["cmnth"] = cos(test["mnth"]/(2*math.pi))
test["smnth"] = sin(test["mnth"]/(2*math.pi))
test["chr"] = cos(test["hr"]/(2*math.pi))
test["shr"] = sin(test["hr"]/(2*math.pi))
test["cseason"] = cos(test["season"]/(2*math.pi))
test["sseason"] = sin(test["season"]/(2*math.pi))
test["cweekday"] = cos(test["weekday"]/(2*math.pi))
test["sweekday"] = sin(test["weekday"]/(2*math.pi))


test.drop('hr', axis=1, inplace=True)
test.drop('mnth', axis=1, inplace=True)



#test["day"] = test["dteday"].dt.day
#test.drop('yr', axis=1, inplace=True)
test.drop('dteday', axis=1, inplace=True)

In [95]:
train.head(5)

,instant,season,yr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt,cmnth,smnth,chr,shr,cseason,sseason,cweekday,sweekday
0,1,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,2.772589,0.987362,0.158484,1.000000,0.000000,0.987362,0.158484,0.577666,0.816273
1,2,1,0,0,6,0,1,0.22,0.2727,0.80,0.0,3.688879,0.987362,0.158484,0.987362,0.158484,0.987362,0.158484,0.577666,0.816273
2,3,1,0,0,6,0,1,0.22,0.2727,0.80,0.0,3.465736,0.987362,0.158484,0.949766,0.312962,0.987362,0.158484,0.577666,0.816273
3,4,1,0,0,6,0,1,0.24,0.2879,0.75,0.0,2.564949,0.987362,0.158484,0.888163,0.459529,0.987362,0.158484,0.577666,0.816273
4,5,1,0,0,6,0,1,0.24,0.2879,0.75,0.0,0.000000,0.987362,0.158484,0.804110,0.594481,0.987362,0.158484,0.577666,0.816273

In [96]:
train.corr()["cnt"]

instant       0.234820
season        0.161126
yr            0.175105
holiday      -0.000435
weekday       0.028402
workingday   -0.018126
weathersit   -0.106078
temp          0.373913
atemp         0.369587
hum          -0.327998
windspeed     0.120310
cnt           1.000000
cmnth        -0.136984
smnth         0.218904
chr          -0.654332
shr           0.107973
cseason      -0.132733
sseason       0.165692
cweekday     -0.034953
sweekday      0.026457
Name: cnt, dtype: float64

In [82]:
train["hum"] = preprocessing.scale(train["hum"])
train["temp"] = preprocessing.scale(train["temp"])
train["atemp"] = preprocessing.scale(train["atemp"])
train["windspeed"] = preprocessing.scale(train["windspeed"])


test["hum"] = preprocessing.scale(test["hum"])
test["temp"] = preprocessing.scale(test["temp"])
test["atemp"] = preprocessing.scale(test["atemp"])
test["windspeed"] = preprocessing.scale(test["windspeed"])

In [97]:
train.head(5)

,instant,season,yr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt,cmnth,smnth,chr,shr,cseason,sseason,cweekday,sweekday
0,1,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,2.772589,0.987362,0.158484,1.000000,0.000000,0.987362,0.158484,0.577666,0.816273
1,2,1,0,0,6,0,1,0.22,0.2727,0.80,0.0,3.688879,0.987362,0.158484,0.987362,0.158484,0.987362,0.158484,0.577666,0.816273
2,3,1,0,0,6,0,1,0.22,0.2727,0.80,0.0,3.465736,0.987362,0.158484,0.949766,0.312962,0.987362,0.158484,0.577666,0.816273
3,4,1,0,0,6,0,1,0.24,0.2879,0.75,0.0,2.564949,0.987362,0.158484,0.888163,0.459529,0.987362,0.158484,0.577666,0.816273
4,5,1,0,0,6,0,1,0.24,0.2879,0.75,0.0,0.000000,0.987362,0.158484,0.804110,0.594481,0.987362,0.158484,0.577666,0.816273

In [98]:
test.head(5)

,instant,season,yr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cmnth,smnth,chr,shr,cseason,sseason,cweekday,sweekday
0,432,1,0,0,4,1,1,0.26,0.2273,0.56,0.3881,0.987362,0.158484,1.000000,0.000000,0.987362,0.158484,0.80411,0.594481
1,433,1,0,0,4,1,1,0.26,0.2727,0.56,0.0000,0.987362,0.158484,0.987362,0.158484,0.987362,0.158484,0.80411,0.594481
2,434,1,0,0,4,1,1,0.26,0.2727,0.56,0.0000,0.987362,0.158484,0.949766,0.312962,0.987362,0.158484,0.80411,0.594481
3,435,1,0,0,4,1,1,0.26,0.2576,0.56,0.1642,0.987362,0.158484,0.888163,0.459529,0.987362,0.158484,0.80411,0.594481
4,436,1,0,0,4,1,1,0.26,0.2576,0.56,0.1642,0.987362,0.158484,0.804110,0.594481,0.987362,0.158484,0.80411,0.594481

In [99]:
train.corr()["cnt"]

instant       0.234820
season        0.161126
yr            0.175105
holiday      -0.000435
weekday       0.028402
workingday   -0.018126
weathersit   -0.106078
temp          0.373913
atemp         0.369587
hum          -0.327998
windspeed     0.120310
cnt           1.000000
cmnth        -0.136984
smnth         0.218904
chr          -0.654332
shr           0.107973
cseason      -0.132733
sseason       0.165692
cweekday     -0.034953
sweekday      0.026457
Name: cnt, dtype: float64

In [100]:
X = train[['cseason','sseason','yr','cmnth','chr','smnth','shr','cweekday','sweekday','holiday','workingday','weathersit','temp','atemp','hum','windspeed']]
y= train['cnt']

X_test_set =test[['cseason','sseason','yr','cmnth','chr','smnth','shr','cweekday','sweekday','holiday','workingday','weathersit','temp','atemp','hum','windspeed']]

In [101]:
X.head(5)

,cseason,sseason,yr,cmnth,chr,smnth,shr,cweekday,sweekday,holiday,workingday,weathersit,temp,atemp,hum,windspeed
0,0.987362,0.158484,0,0.987362,1.000000,0.158484,0.000000,0.577666,0.816273,0,0,1,0.24,0.2879,0.81,0.0
1,0.987362,0.158484,0,0.987362,0.987362,0.158484,0.158484,0.577666,0.816273,0,0,1,0.22,0.2727,0.80,0.0
2,0.987362,0.158484,0,0.987362,0.949766,0.158484,0.312962,0.577666,0.816273,0,0,1,0.22,0.2727,0.80,0.0
3,0.987362,0.158484,0,0.987362,0.888163,0.158484,0.459529,0.577666,0.816273,0,0,1,0.24,0.2879,0.75,0.0
4,0.987362,0.158484,0,0.987362,0.804110,0.158484,0.594481,0.577666,0.816273,0,0,1,0.24,0.2879,0.75,0.0

In [102]:
X_test_set.head(5)

,cseason,sseason,yr,cmnth,chr,smnth,shr,cweekday,sweekday,holiday,workingday,weathersit,temp,atemp,hum,windspeed
0,0.987362,0.158484,0,0.987362,1.000000,0.158484,0.000000,0.80411,0.594481,0,1,1,0.26,0.2273,0.56,0.3881
1,0.987362,0.158484,0,0.987362,0.987362,0.158484,0.158484,0.80411,0.594481,0,1,1,0.26,0.2727,0.56,0.0000
2,0.987362,0.158484,0,0.987362,0.949766,0.158484,0.312962,0.80411,0.594481,0,1,1,0.26,0.2727,0.56,0.0000
3,0.987362,0.158484,0,0.987362,0.888163,0.158484,0.459529,0.80411,0.594481,0,1,1,0.26,0.2576,0.56,0.1642
4,0.987362,0.158484,0,0.987362,0.804110,0.158484,0.594481,0.80411,0.594481,0,1,1,0.26,0.2576,0.56,0.1642

In [103]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)
print X_train.shape
print X_test.shape

(8164, 16)
(2722, 16)

In [123]:
from sklearn.neighbors import KNeighborsRegressor

kneighbor_regression = KNeighborsRegressor(n_neighbors=6)
kneighbor_regression.fit(X_train, y_train)


print kneighbor_regression.score(X_train, y_train)
print kneighbor_regression.score(X_test, y_test)

0.937274814096
0.909447839277

In [124]:
y_pred_test_real = kneighbor_regression.predict(X_test_set)

y_pred_test_real= exp(y_pred_test_real)
print y_pred_test_real

[   6.63967124    5.5271928     2.74945927 ...,  139.21976426  120.41628951
  108.58128375]

In [125]:
y_pred_test_real_final = np.ndarray(shape=(len(y_pred_test_real),2), dtype=int)

for i in range (0,len(y_pred_test_real)):
    y_pred_test_real_final[i,0] = firstColumnInd[i]
    y_pred_test_real_final[i,1] = round(y_pred_test_real[i],0)
    
print y_pred_test_real_final

[[  432     7]
 [  433     6]
 [  434     3]
 ...,
 [17377   139]
 [17378   120]
 [17379   109]]

In [126]:
numpy.savetxt("predictive_count.csv", y_pred_test_real_final, delimiter=",",fmt='%d')